version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.5.7-management
    container_name: rabbitmq
    ports:
        - "5672:5672"
        - "15672:15672"
        # - "15671:15671"
        # - "5671:5671"
    environment:
        RABBITMQ_DEFAULT_USER: myuser
        RABBITMQ_DEFAULT_PASS: mypassword
        RABBITMQ_SSL_CERTFILE: /cert_rabbitmq/server_certificate.pem
        RABBITMQ_SSL_KEYFILE: /cert_rabbitmq/server_key.pem
        RABBITMQ_SSL_CACERTFILE: /cert_rabbitmq/ca_certificate.pem
        # RABBITMQ_SSL_VERIFY: verify_none
    volumes:
      - ./cert_rabbitmq:/cert_rabbitmq
