version: '3.7'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    command: mysqld --max_allowed_packet=2000M --wait_timeout=28800 --interactive_timeout=28800
    volumes:
      - ./mysql_setup:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
