version: '3.7'

services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./minio_data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: myuser
      MINIO_SECRET_KEY: mypassword
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
